CREATE SCHEMA IF NOT EXISTS PAYMENTS;
CREATE TABLE IF NOT EXISTS PAYMENTS.PAYMENT
(
    ID                    UUID PRIMARY KEY,
    CREATED_AT            TIMESTAMP   NOT NULL DEFAULT NOW(),
    PAID_AT               TIMESTAMP,
    STATUS                VARCHAR(15) NOT NULL,
    AUTHORIZATION_CODE    VARCHAR(36),
    UNIQUE_SEQUENCE_NUMBER BIGINT,
    AMOUNT                DECIMAL     NOT NULL,
    USER_ID               VARCHAR(36) NOT NULL
);
